# Site settings
title:          "MLFL"
description:    "Machine Learning & Friends Lunch"
baseurl:        ""
url:            "https://umass-mlfl.github.io"

# MLFL settings
current_semester_name: "Fall 2025"
current_sem_start: 2025-09-02
current_sem_end: 2025-12-17

# Author
author:
  name:         Kalpesh Krishna, Neha Kennard, Wenlong Zhao, Ankita Gupta, Sankaran Vaidyanathan, Dhruv Agarwal

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, process_info.py ]

keep_files: [assets]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
